version: "3"
services:
  kupiback:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "4000:3000"
    restart: unless-stopped

  postgres:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - ./pg-data:/var/lib/postgresql/data2/pgdata
    restart: unless-stopped

  kupifront:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "8081:80"
    restart: unless-stopped
